language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t crstnrm/docker-course -f Dockerfile .

script:
  - docker run -e CI=true crstnrm/docker-course npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI